### ISSUE TITLE
api configuration? 

### ISSUE THREAD

**Issue by sleepysam** [danvn/rest-api#1]
# deez nuts ?
![giphy-4](https://cloud.githubusercontent.com/assets/13042701/24466125/f1c62de2-146c-11e7-94df-83c133f2c671.gif)

**Comment by danvn** [comment]
Have deez issues been resolved? 

Let me know,

Dan

**Comment by sleepysam** [comment]
Deez nuts have been resolved.
Thanks for the hard work here @danvn 🙇 

- Please re-open this issue as needed 👍 
- Closing down for now 🔥 ⬇️
